---
layout: narrow_page
title: The Good News
permalink: /good-news/
---
= The Good News

= The Good News

News often informs us of what may happen in our future. You may hear of good or bad things happening in the world, and you may change your behavior if you know what's coming. If a weather report tells of a coming storm you will take action to prepare for it. The news you hear on the internet or TV might give you clues as to what's going to happen in your the near future. The Good News presented here also tells of things that are going to happen in the future. It tells us of things that affect us today, as well as many important things in our future. It tells what comes after we die. And unlike weather reports, news here is completely accurate and will not change.

Please spend a few minutes reading about this invaluable Good News.

== God Gave Us the Bible

The Bible is a supernatural book given to us by God footnote:[2 Timothy 3:16-17] that he has promised to preserve for us. footnote:[1 Peter 1:25]

We can trust the Bible because it has proven to be a supernatural book, telling us of hundreds of things before they happened, often hundreds of years in advance. The Bible tells us many things about the future.

All Good News presented here comes from the Bible. The quotes you see here are all verses taken from the Bible.

== The Bible Says *All* Have Sinned

Have you ever done anything you knew was wrong? Have you ever lied to someone or stolen something? We've have all done things we know are wrong, and the Bible calls this sin footnote:[1 John 3:4].

[.scripture]
[quote, Romans 3:23]
____
For *all have sinned*, and come short of the glory of God;
____

The Bible says you have law of God written on you heart. This is how you know when you've done something wrong.

[.scripture]
[quote, Romans 2:15]
____
15 Which shew the work of the *law written in their hearts*, their conscience
also bearing witness, and their thoughts the mean while accusing or else
excusing one another;)
____

==== But God did not create man to be wicked.

[.scripture]
[quote, Ecclesiastes 7:29]
____
Lo, this only have I found, that God hath made man upright; but they have sought out many inventions.
____

== God is Holy and Just

[.scripture]
[quote, Psalms 89:14]
____
Justice and judgment are the habitation of thy throne: mercy and truth
shall go before thy face.
____

Because God is just and will punish the wicked for their sins. Only an unjust judge would let the wicked go unpunished. In his righteousness he is angry with the wicked because of the sins they commit.

[.scripture]
[quote, Psalm 7:11]

____
God judgeth the righteous, and God is angry with the wicked every day.
____

[.scripture]
[quote, Numbers 14:18]
____
The LORD is longsuffering, and of great mercy, forgiving iniquity and
transgression, and *by no means clearing the guilty*, visiting the iniquity of
the fathers upon the children unto the third and fourth generation.
____

== The Wages of Sin is Death

The Bible says the wages of sin is death.footnote:[Romans 6:23]

[.scripture]
[quote, James 1:15]
____
Then when lust hath conceived, it bringeth forth sin: *and sin, when it is
finished, bringeth forth death*.
____

=== Punishment is Eternity in Hell

[.scripture]
[quote, Matthew 13:49-50]
____
So shall it be at the end of the world: the angels shall come forth, and
sever the wicked from among the just,
And shall cast them into the furnace of fire: there shall be wailing and
gnashing of teeth.
____


The lake of fire is the punishment for anyone who has sinned. It doesn't matter
if you haven't committed any of *_"really bad"_* sins. The Bible says anyone who has sinned
in any way has broken part of God's law is guilty of all of it.
[.scripture]
[quote, James 2:10]
____
For whosoever shall keep the whole law, and yet *offend in one point, he is
guilty of all*.
____

Regardless of what sins you have committed you will be punished with enternity in hell.

[.scripture]
[quote, Romans 1:18]
____
For the wrath of God is revealed from heaven against all ungodliness and
unrighteousness of men, who hold the truth in unrighteousness;
____

== But God does not want anyone to perish

[.scripture]
[quote, 2 Peter 3:9]
____
The Lord is not slack concerning his promise, as some men count slackness;
but is longsuffering to us-ward, *not willing that any should perish, but that
all should come to repentance.*
____

Hell was prepared for the 'devil and his angels' footnote:[Matthew 25:41, Ecclesiastes 7:29] and God does not want any of us to perish there.

== God made a way for you to be saved through Jesus Christ

==== Jesus lived the sinless life you did not

The Bible says that Jesus "did no sin, neither was guile found in his mouth:" footnote:[1 Peter 2:22].
And John calls him "Jesus Christ the righteous" footnote:[1 John 2:1].

==== Jesus died the death you deserved

[.scripture]
[quote, Romans 5:8]
____
But God commendeth his love toward us, in that, while we were yet sinners,
Christ died for us.
____

=== Jesus exchanged his righteousness for your sins

image::/images/imputed-righteousness.svg[Static]

[.scripture]
[quote, 2 Corinthians 5:21]
____
For he hath made him to be sin for us, who knew no sin; that we might be
made the righteousness of God in him.
____

Jesus never sinned and did not deserve to die. Jesus lived a perfectly
righteous life and died on the cross as if he was a sinner. When he died
he took your sins upon himself and offers you his righteousness in return.

== Believe on Jesus and you will be saved

Jesus can be your Saviour. All you must do is believe in him.

[.scripture]
[quote, John 3:16]
____
For God so loved the world, that he gave his only begotten Son, that
*whosoever believeth in him* should not perish, but have everlasting life.
____

[.scripture]
[quote, Romans 4:5]
____
But to him that *worketh not*, but *believeth* on him that justifieth the ungodly, his *faith is counted for righteousness*.
____


This is the good news. By believing that Jesus Christ bore your sin on the cross you can know that when you die you will go to heaven. Not because of something you did, but because of what he did for you. Because he bore your sins you do not have to fear hell, because *his righteousness is enough* to get you into heaven. You don't have to worry about being good enough to be acceptable to God, because *Jesus already was good enough*. Because you can have a right relationship with God through Jesus Christ you do not need to fear anything that may happen.

[.scripture]
[quote, John 11:25-26]
____
Jesus said unto her, I am the resurrection, and the life: he that
  believeth in me, though he were dead, yet shall he live:
And whosoever liveth and believeth in me shall never die. *Believest thou
    this*?
____
